config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users

  scope module: 'public_api' do
    root 'home#homepage'
    get 'public_diets', to: 'public_diets#index'
    get 'public_diets/new', to: 'public_diets#new'
    get 'public_diets/:id', to: 'public_diets#show', as: 'public_diet_show'
    post 'public_diets', to: 'public_diets#create', as: 'public_diet_create'
  end

  scope module: 'private_api' do
    get 'user/:used_id/homepage', to: 'user_home#homepage'
    post 'diets/:id/send_report', to: 'diets#send_report', as: 'diet_send_report'
    resources :diets
    resources :meals
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/diet.rb
class Diet < ApplicationRecord
  has_one :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :meals
  scope :without_owner, -> { where(owner_id: nil) }
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_one :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :confirmable

  has_many :diets, through: :diet_user_assignments
  has_many :meals

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:danger] = 'Not authorized'
    redirect_to(request.referer || root_path)
 end
end
end

app/controllers/concerns/meal_properties_parser.rb
module MealPropertiesParser
  def fetch_meal_properties(title)
    response = HTTParty.get("https://api.calorieninjas.com/v1/nutrition",
                            headers: headers, query: { 'query' => title })
    meal_hash = JSON.parse(response.body).fetch('items')
    calories = meal_hash.reduce(0) { |acc, el| acc + el.fetch('calories') }
    grams = meal_hash.reduce(0) { |acc, el| acc + el.fetch('serving_size_g') }
    nutrients = {}
    meal_hash.each do |hash|
       hash.each do |key, value|
          nutrients[key].nil? ? nutrients[key] = value : nutrients[key] += value
       end
    end
    { calories: calories, grams: grams, nutrients: nutrients }

  rescue HTTParty::Error
      puts "!!!!!API ERROR DETECTED!!!!!!!#{response}!!!!!!!!API ERROR DETECTED!!!!!!!"
  end

  private

  def headers
    {'X-Api-Key' => ENV['NINJAS_API_KEY']}
  end
end

app/controllers/private_api/diets_controller.rb
module PrivateApi
  class DietsController < PrivateApiController
    include MealPropertiesParser
    before_action :set_diet, only: %i[ destroy edit update show send_report]
    before_action :authorize_diet!

    def index
      @diets = policy_scope(Diet)
    end

    def show
      @meals = current_user.meals.where(eat_time: 1.day.ago..Time.now)
    end

    def new
      @diet = Diet.new
    end

    def create
      @diet = Diet.new(diet_params)
      calculate_diet_properties
      @diet.owner_id = current_user.id
      if @diet.save
        redirect_to diet_path(@diet)
      else
        render :new
      end
    end

    def edit; end

    def update
      @diet.update(diet_params)
      calculate_diet_properties
      if @diet.save
        redirect_to diet_path(@diet)
      else
        render :edit
      end
    end

    def destroy
      @diet.delete
      redirect_to diets_path
    end

    def send_report
      SendReportJob.perform_async('user_id' => current_user.id, 'diet_id' => @diet.id)

      redirect_to diets_path
    end

    private

    def calculate_diet_properties
      data = fetch_meal_properties(diet_params[:components])
      @diet.total_calories = data.fetch(:calories)
      @diet.nutrients = data.fetch(:nutrients)
    end

    def diet_params
      params.require(:diet).permit(:name, :components, :description)
    end

    def set_diet
      @diet = Diet.find(params[:id])
    end

    def authorize_diet!
      authorize(@diet || Diet)
    end
  end
end

app/controllers/private_api/meals_controller.rb
module PrivateApi
  class MealsController < PrivateApiController
    include MealPropertiesParser
    before_action :find_meal, only: [:update, :edit, :destroy, :show]
    before_action :authorize_meal

    def index
      @meals = policy_scope(Meal)
      @meals = @meals.where(eat_time: range_params[:from]..Time.now) if range_params[:from]
    end

    def show
      @meal = Meal.find(params[:id])
    end

    def new
      @meal = Meal.new
    end

    def create
      @meal = current_user.meals.build(meals_params)
      calculate_meal_properties
      if @meal.save
        redirect_to meal_path(@meal)
      else
        render :new
      end
    end

    def edit
    end

    def update
      @meal.update(meals_params)
      calculate_meal_properties
      if @meal.save
        redirect_to meal_path(@meal)
      else
        render :edit
      end
    end

    def destroy
      if @meal.delete
        redirect_to meals_path
      end
    end

    def range
      @meals = Meal.where(eat_time: range_params[:from]..Time.now)
    end

    private

    def range_params
      params.permit(:from)
    end

    def find_meal
      @meal = Meal.find params[:id]
    end

    def authorize_meal
      authorize(@meal || Meal)
    end

    def meals_params
      params.require(:meal).permit(:title, :eat_time)
    end

    def calculate_meal_properties
      data = fetch_meal_properties(meals_params[:title])
      @meal.calories = data.fetch(:calories)
      @meal.grams = data.fetch(:grams)
      @meal.nutrients = data.fetch(:nutrients)
    end

  end
end

app/controllers/private_api/private_api_controller.rb
module PrivateApi
class PrivateApiController < ApplicationController
    include Authorization
    before_action :authenticate_user!
    after_action :verify_authorized
  end
end

app/controllers/private_api/user_home_controller.rb
module PrivateApi
  class UserHomeController < PrivateApiController
    include Pundit
  def homepage
  end
end
end

app/controllers/public_api/home_controller.rb
module PublicApi
  class HomeController < ApplicationController
    def homepage
    end
  end
end

app/controllers/public_api/public_diets_controller.rb
module PublicApi
class PublicDietsController < ApplicationController
  include MealPropertiesParser
  before_action :find_diet, only: %i[show]

   def index
     @diets = Diet.without_owner
   end

   def show
   end

   def new
     @diet = Diet.new
   end

   def create
     @diet = Diet.new(diet_params)
     calculate_diet_properties
     if @diet.save
       redirect_to public_diets_path(@diet)
     else
       render :new
   end
 end

   private

   def find_diet
     @diet = Diet.find(params[:id])
   end

   def diet_params
     params.require(:diet).permit(:name, :components, :description)
   end

   def calculate_diet_properties
      data = fetch_meal_properties(diet_params[:components])
      @diet.total_calories = data.fetch(:calories)
      @diet.nutrients = data.fetch(:nutrients)
   end
end
end

app/views/home/homepage.html.erb
<h1>Homepage</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title> Healthy App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>
    <%=render 'users/header'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class = 'container'>
     <% flash.each do |_type, msg| %>
        <div style = 'background-color: red;'>
          <%= msg %>
        </div>
     <% end %>

    <%= yield %>
    <div/>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/private_api/diets/_diet.html.erb
<table class="table">
  <thead>
    <tr class="headers">
      <th scope="col">Diet name</th>
      <th scope="col">Description</th>
      <th scope="col">Components</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"> <%= diet.name %></th>
      <br>
      <br>
      <td><%= diet.description %></td>
      <td><%= diet.components %></td>
    </tr>
      <%= link_to "View Diet", diet_path(diet.id), method: :get, class:"button" %>
  </tbody>
</table>

<style>
body {
background: radial-gradient(circle at 10% 20%, rgb(215, 223, 252) 0%, rgb(255, 255, 255) 0%, rgb(215, 223, 252) 84%);
}
h1 {
  color: #800080;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
table, th, td{
  border: 4px solid;
  margin-left: auto;
  margin-right: auto;
}
.table {
  color: #4682B4;
  font-family: Comic Sans MS, Comic Sans, cursive;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.headers {
  color: #00008B;
  font-family: fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}

</style>

app/views/private_api/diets/edit.html.erb
<style>
body {
 background: radial-gradient(circle at 10% 20%, rgba(91, 173, 254, 0.46) 0%, rgba(91, 224, 254, 0.46) 47.2%, rgba(170, 254, 235, 0.43) 90%);
}
h1 {
  color: #800080;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.name {
  color: #D2691E;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}

.description {
  color: #D2691E;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.components{
  color: #D2691E;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.button {
  background-color:#44c767;
 border-radius:28px;
 border:1px solid #18ab29;
 display:inline-block;
 cursor:pointer;
 color:#ffffff;
 font-family:Arial;
 font-size:17px;
 padding:16px 31px;
 text-decoration:none;
 text-shadow:0px 1px 0px #2f6627;
  margin: auto;
  display: block;
}
.button:hover {
 background-color:#5cbf2a;
}

</style>





<h1>Edit your diet</h1>
<div class="name"><%= form_for @diet do |f| %>
 <%= f.label :name, "Your diet name: " %>
 <%= f.text_field :name%>
</div>

  <div class="description"<%= f.label :description, "Description: " %>
  <%= f.text_field :description %>
  </div>
  <div class="components"<%= f.label :components, "Components: " %>
  <%= f.text_area :components %>
   </div>
   <br>
  <%= f.submit "Update Your Diet", class: "button" %>
<% end %>

app/views/private_api/diets/index.html.erb
<style>
body {
background: radial-gradient(circle at 10% 20%, rgb(215, 223, 252) 0%, rgb(255, 255, 255) 0%, rgb(215, 223, 252) 84%);
}
h1 {
  color: #800080;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
table, th, td{
  border: 4px solid;
  margin-left: auto;
  margin-right: auto;
}
.table {
  color: #4682B4;
  font-family: Comic Sans MS, Comic Sans, cursive;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.headers {
  color: #00008B;
  font-family: fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.button {
 background-color:#44c767;
 border-radius:28px;
 border:1px solid #18ab29;
 display:inline-block;
 cursor:pointer;
 color:#ffffff;
 font-family:Arial;
 font-size:17px;
 padding:16px 31px;
 text-decoration:none;
 text-shadow:0px 1px 0px #2f6627;
  margin: auto;
}
.button:hover {
 background-color:#5cbf2a;
}

</style>

<h1>Diets: </h1>
<%= link_to "Create New Diet", new_diet_path, class:"button"%>
<% @diets.each do |diet| %>
<%= render partial: 'diet', object: diet%>
  <% end %>

app/views/private_api/diets/show.html.erb
<style>
body {
  background: radial-gradient(circle at 0% 0.5%, rgb(241, 241, 242) 0.1%, rgb(224, 226, 228) 100.2%);
}
h1 {
  color: #D2691E;
  font-family: Gill Sans, sans-serif;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
  border: 3px solid #008B8B;
  padding: 3px;
}
h4 {
  color: #008B8B;
  font-family: Gill Sans, sans-serif;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.all{
  color: #008B8B;
  font-family: Gill Sans, sans-serif;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.nutrients {
  color: #556B2F;
}
.button {
 background-color:#D2691E;
 border-radius:28px;
 border:1px solid #18ab29;
 display:inline-block;
 cursor:pointer;
 color:#ffffff;
 font-family:Arial;
 font-size:17px;
 padding:16px 31px;
 text-decoration:none;
 text-shadow:0px 1px 0px #2f6627;
  margin: auto;
  display: block;
  width: 180px;
  text-align: center;
}
.button:hover {
 background-color:#008B8B;
}
p{
  color: #D2691E;
  font-family: Gill Sans, sans-serif;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
</style>

<h1><%=@diet.name %></h1>
    <h4>Description: <%= @diet.description %></h4>
    <h4 class="all">Components: <%= @diet.components %></h4>
  <h4>total_calories: <%= @diet.total_calories %></h4>
  <p class="nutrients"><b>Nutrients:</b></p>
  <% @diet.nutrients.except('name').each do |key, v| %>
    <p><%= key.humanize %>: <%= v.truncate(2).to_s %></p>
  <% end %>
  <% if @diet.owner_id %>
  <p>Owner: <%= User.find(@diet.owner_id).email %></p>
<% else %>
  <p>owner: Without owner</p>
<% end %>

<% if policy(@diet).destroy? %>
  <%= button_to "Destroy Diet", diet_path(@diet), method: :delete, class:"button" %>
<% end %>
</br>
  <%= button_to "Send report", diet_send_report_path(@diet), method: :post, class:"button" %>
<h4>Diet total calories: <%= @diet.total_calories %></h4>
<h4>Your eaten calories during the last day: <%= @meals.reduce(0) { |acc, el| acc +  el.calories } %></h4>
<h1>Your meals: </h1>
<% @meals.each do |meal| %>
  <%= render partial: 'private_api/meals/meal', object: meal %>
<% end %>

app/views/private_api/meals/index.html.erb
<style>
body {
background: radial-gradient(circle at 10% 20%, rgb(215, 223, 252) 0%, rgb(255, 255, 255) 0%, rgb(215, 223, 252) 84%);
}
h1 {
  color: #800080;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
table, th, td{
  border: 4px solid;
  margin-left: auto;
  margin-right: auto;
}
.table {
  color: #4682B4;
  font-family: Comic Sans MS, Comic Sans, cursive;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.headers {
  color: #00008B;
  font-family: fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.button {
 background-color:#44c767;
 border-radius:28px;
 border:1px solid #18ab29;
 display:inline-block;
 cursor:pointer;
 color:#ffffff;
 font-family:Arial;
 font-size:17px;
 padding:16px 31px;
 text-decoration:none;
 text-shadow:0px 1px 0px #2f6627;
  margin: auto;
  text-align: center;
}
.button:hover {
 background-color:#5cbf2a;
}
</style>

<%= button_to "Add Meal", new_meal_path, method: :get, class:"button" %>

<h1>Meals: </h1>
<%= link_to "ONE DAY", meals_path(from: 1.day.ago), class: 'button' %>
<%= link_to "ONE WEEK", meals_path(from: 1.week.ago), class: 'button' %>
<%= link_to "ONE MONTH", meals_path(from: 1.month.ago), class: 'button' %>
<%= link_to "ONE YEAR", meals_path(from: 1.year.ago), class: 'button' %>
<% @meals.each do |meal| %>
<%= render partial: 'meal', object: meal%>
<% end %>

app/views/private_api/meals/show.html.erb
<style>
body {
  background: radial-gradient(circle at 0% 0.5%, rgb(241, 241, 242) 0.1%, rgb(224, 226, 228) 100.2%);
}
h1 {
  color: #D2691E;
  font-family: Gill Sans, sans-serif;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
  border: 3px solid #008B8B;
  padding: 3px;
}
h4 {
  color: #008B8B;
  font-family: Gill Sans, sans-serif;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.all{
  color: #008B8B;
  font-family: Gill Sans, sans-serif;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.nutrients {
  color: #556B2F;
}
.button {
 background-color:#D2691E;
 border-radius:28px;
 border:1px solid #18ab29;
 display:inline-block;
 cursor:pointer;
 color:#ffffff;
 font-family:Arial;
 font-size:17px;
 padding:16px 31px;
 text-decoration:none;
 text-shadow:0px 1px 0px #2f6627;
  margin: auto;
  display: block;
}
.button:hover {
 background-color:#008B8B;
}
p{
  color: #D2691E;
  font-family: Gill Sans, sans-serif;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
</style>

<h1><%=@meal.title %></h1>
    <p class="nutrients"><b>Nutrients:</b></p>
    <% @meal.nutrients.except('name').each do |key, v| %>
      <p><%= key.humanize %>: <%= v.truncate(2).to_s %></p>
    <% end %>
    <p class="calories"><b>Calories:</b></p>
  <h4><%= @meal.calories %></h4>
  <p class="grams"><b>Grams:</b></p>
  <h4><%= @meal.grams.truncate(2) %></h4>

  <%= button_to "Edit Meal", edit_meal_path, method: :get, class:"button" %>

app/views/public_api/home/homepage.html.erb
<style>
body {
  background: radial-gradient(circle at 10% 20%, rgb(220, 217, 249) 0%, rgb(172, 224, 217) 89.8%);
}
h1 {
  color: #D2691E;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
h5 {
  color: #800000;
  border: 15px solid #FFF5EE;
  padding: 35px;
  font-family: Gill Sans, sans-serif;

}
.button {
  background-color:#44c767;
 border-radius:28px;
 border:1px solid #18ab29;
 display:inline-block;
 cursor:pointer;
 color:#ffffff;
 font-family:Arial;
 font-size:17px;
 padding:16px 31px;
 text-decoration:none;
 text-shadow:0px 1px 0px #2f6627;
  margin: auto;
  display: block;
}
.button:hover {
 background-color:#5cbf2a;
}
</style>
<h1>
Welcome to Pro DiEt App!
</h1>
</br>
<h5>This is an app for tracking your daily eaten meal calories and nutrients. You can get the email with the report of eaten calories, nutrients and its percentage up/down compared to previous day. You can also create a daily diet(meal plan for each day) and see how many calories and nutrients it will consume. You can check out all eaten meals, calories, and nutrients on daily basis/monthly basis, as well as ask to build report for some period of time. You are free to enable/disable ability to get daily/weekly/monthly reports or custom date reports.</h5>

<br>

<%= button_to "Create Your Trial Diet", public_diets_new_path, method: :get, class:"button" %>

app/views/public_api/public_diets/index.html.erb
<style>
body {
background: radial-gradient(circle at 10% 20%, rgb(215, 223, 252) 0%, rgb(255, 255, 255) 0%, rgb(215, 223, 252) 84%);
}
h1 {
  color: #800080;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
table, th, td{
  border: 4px solid;
  margin-left: auto;
  margin-right: auto;
}
.table {
  color: #4682B4;
  font-family: Comic Sans MS, Comic Sans, cursive;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.headers {
  color: #00008B;
  font-family: fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.button {
 background-color:#44c767;
 border-radius:28px;
 border:1px solid #18ab29;
 display:inline-block;
 cursor:pointer;
 color:#ffffff;
 font-family:Arial;
 font-size:17px;
 padding:16px 31px;
 text-decoration:none;
 text-shadow:0px 1px 0px #2f6627;
  margin: auto;
}
.button:hover {
 background-color:#5cbf2a;
}

</style>







<h1>Diets: </h1>
<% @diets.each do |diet| %>
  <%= link_to "View Diet", public_diet_show_path(diet.id), method: :get, class:"button" %>
<table class="table">
  <thead>
    <tr class="headers">
      <th scope="col">Diet name</th>
      <th scope="col">Description</th>
      <th scope="col">Components</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"> <%= diet.name %></th>
      <br>
      <br>
      <td><%= diet.description %></td>
      <td><%= diet.components %></td>
    </tr>
  </tbody>
</table>
  <% end %>

app/views/public_api/public_diets/new.html.erb
<style>
body {
 background: radial-gradient(circle at 10% 20%, rgba(91, 173, 254, 0.46) 0%, rgba(91, 224, 254, 0.46) 47.2%, rgba(170, 254, 235, 0.43) 90%);
}

h1 {
  color: #800080;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}

.name {
  color: #D2691E;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
}
.diet {
  color: #D2691E;
  font-family: Marker Felt, fantasy;
  margin-top: 1rem;
  padding-bottom: 0.1rem;
  text-align: center;
 }

  .diet {
    color: #D2691E;
    font-family: Marker Felt, fantasy;
    margin-top: 1rem;
    padding-bottom: 0.1rem;
    text-align: center;
  }

  .components {
      color: #D2691E;
      font-family: Marker Felt, fantasy;
      margin-top: 1rem;
      padding-bottom: 0.1rem;
      text-align: center;
}
.button {
 background-color:#44c767;
 border-radius:28px;
 border:1px solid #18ab29;
 display:inline-block;
 cursor:pointer;
 color:#ffffff;
 font-family:Arial;
 font-size:17px;
 padding:16px 31px;
 text-decoration:none;
 text-shadow:0px 1px 0px #2f6627;
  margin: auto;
  display: block;
}
.button:hover {
 background-color:#5cbf2a;
}

  </style>
<div>
      <h1>Create Your Test Diet</h1>
       <div class="name"><%= form_for @diet, url: public_diet_create_path do |f| %>
        <%= f.label :name, "Your diet name: " %>
        <%= f.text_field :name%>
        </div>
        <br>
       <div class="diet">
        <%= f.label :description, "Description: " %>
        <%= f.text_field :description %>
        </div>
        <br>
    <div class="components">
        <%= f.label :components, "Components: " %>
        <%= f.text_area :components %>
        </div>
        <br>
        <%= f.submit "Create & Save", class: "button" %>
      <% end %>
 </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>